controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

adapters:
  resource:
    path: ../srcClean/Adapter/Primary/
    namespace: Clean\Adapter\Primary
  type: attribute

Login:
    path: /api/users/login
